<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LikesController;
use App\Http\Controllers\StoriesController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PostTagsController;
use Illuminate\Support\Facades\Route;



Route::group(['middleware' => 'auth:sanctum'], function () {
    Route::post('account/changepass', [AuthController::class, 'ChangePass']);
    Route::post('maps/mapsearch', [AuthController::class, 'SearchMaps']);
    Route::post('webprofile', [AuthController::class, 'user']);
    Route::post('account/updateprofile', [ProfileController::class, 'CompeleteProfile']);
    Route::post('post/create', [PostController::class, 'CreatePost']);
    Route::post('comment/create', [CommentsController::class, 'CreateComment']);
    Route::post('like/create', [LikesController::class, 'CreateLike']);
    Route::post('account/profile', [ProfileController::class, 'UserProfile']);
    Route::post('userpost/posts', [PostController::class, 'UserPosts']);
    Route::get('post/singlepost/{id}', [PostController::class, 'SinglePost']);
    Route::post('story/create', [StoriesController::class, 'CreateStory']);
    Route::post('story/userstories', [StoriesController::class, 'UserStories']);
    Route::post('story/otheruserstories', [StoriesController::class, 'OtherUserStories']);
    Route::post('story/storyviews', [StoriesController::class, 'StoryViews']);
    Route::post('post/tags', [PostTagsController::class, 'PostTags']);
    Route::post('tags/search', [PostTagsController::class, 'SearchTags']);
    Route::post('post/search/bytitle', [PostController::class, 'SearchPostByTitle']);
    Route::post('post/search/bytitle', [PostController::class, 'SearchPostByTitle']);
    Route::post('tags/searchonlytags', [PostTagsController::class, 'SearchOnlyTags']);
    Route::post('user/follow', [App\Http\Controllers\FollowersController::class, 'FollowUser']);
    Route::post('user/followinglist', [App\Http\Controllers\FollowersController::class, 'UserFollowing']);
    Route::post('user/usersearch', [UserController::class, 'UserSearch']);
    Route::post('posts/followingposts', [PostController::class, 'FollowingPosts']);
    Route::post('follow/followercounter', [App\Http\Controllers\FollowersController::class, 'FollowerCounter']);
    Route::post('follow/followingcounter', [App\Http\Controllers\FollowersController::class, 'FollowingCounter']);
    Route::post('user/followerslist', [App\Http\Controllers\FollowersController::class, 'UserFollowers']);
    Route::post('user/followerslist', [App\Http\Controllers\FollowersController::class, 'UserFollowers']);
    Route::post('user/unfollow', [App\Http\Controllers\FollowersController::class, 'UnfollowUsers']);
    Route::post('user/regionsearch', [App\Http\Controllers\ProfileController::class, 'RegionSearch']);
    Route::post('chat/newpvm', [App\Http\Controllers\MessagesController::class, 'SendPrivateMessage'])->middleware(['auth:sanctum', 'seen']);
    Route::post('message', [App\Http\Controllers\Controller::class, 'SendPush']);
    Route::post('chat/usermessages', [App\Http\Controllers\MessagesController::class, 'UserMessages']);
    Route::post('chat/userchats', [App\Http\Controllers\MessagesController::class, 'UserChats']);
    Route::post('user/profiles', [App\Http\Controllers\PostController::class, 'OtherUserProfiles']);
    Route::post('chat/seenmessage', [App\Http\Controllers\MessagesController::class, 'SeenMessage']);
    Route::post('posts/explore', [App\Http\Controllers\PostController::class, 'Explore']);
    Route::post('maps/nearby', [App\Http\Controllers\UserController::class, 'NearBy']);
    Route::post('posts/delete', [App\Http\Controllers\PostController::class, 'DeletePost']);
    Route::post('stories/delete', [App\Http\Controllers\StoriesController::class, 'DeleteStory']);
    Route::post('reports/create', [App\Http\Controllers\ReportUsersController::class, 'CreateReport']); // nreed more edit
    Route::post('chats/deletechat', [App\Http\Controllers\MessagesController::class, 'DeleteChat']);
    Route::post('chats/deletemessage', [App\Http\Controllers\MessagesController::class, 'DeleteMessage']);
    Route::post('intrests/create', [App\Http\Controllers\IntrestedController::class, 'CreateIntrest']);
    Route::post('intrests/userintrests', [App\Http\Controllers\IntrestedController::class, 'Userintrests']);
    Route::post('intrests/tags', [App\Http\Controllers\IntrestedController::class, 'IntrestTags']);
    Route::post('intrests/cats', [App\Http\Controllers\IntrestedController::class, 'IntrestCats']);
    Route::post('maps/updateloc', [App\Http\Controllers\UserController::class, 'Updateloc']);
    Route::post('vitrin/create', [App\Http\Controllers\ProfileController::class, 'createVitrinPhotos']);
    Route::post('intrests/createlike', [App\Http\Controllers\IntrestedController::class, 'CreateLike']);
    Route::post('intrests/likedpeople', [App\Http\Controllers\IntrestedController::class, 'LikedPeople']);
    Route::post('vitrin/uservitrin', [App\Http\Controllers\ProfileController::class, 'UserVitrin']);
    Route::post('fcm/create', [App\Http\Controllers\UserController::class, 'CreateFcm']);
    Route::post('block/create', [App\Http\Controllers\BlockUserController::class, 'Create']);
    Route::post('block/list', [App\Http\Controllers\BlockUserController::class, 'BlockList']);
    Route::post('account/createlanguage', [App\Http\Controllers\ProfileController::class, 'CreateLanguage']);
    Route::post('savepost/create', [App\Http\Controllers\PostController::class, 'CreateSavedPost']);
    Route::post('savepost/list', [App\Http\Controllers\PostController::class, 'SavedList']);
    Route::post('follow/pendings', [App\Http\Controllers\FollowersController::class, 'Pendings']);
    Route::post('follow/changestatus', [App\Http\Controllers\FollowersController::class, 'FollowChangeStatus']);
    Route::post('activity/list', [App\Http\Controllers\ActivityController::class, 'Activites']);
    Route::post('business/cats', [App\Http\Controllers\BusinessController::class, 'BusinessCats']);
    Route::post('business/addbusiness', [App\Http\Controllers\BusinessController::class, 'AddBusiness']);
    Route::post('business/addpost', [App\Http\Controllers\BusinessController::class, 'CreatePosts']);
    Route::post('business/follow', [App\Http\Controllers\BusinessController::class, 'FollowABusiness']);
    Route::post('business/profile', [App\Http\Controllers\BusinessController::class, 'BusinessProfile']);
    Route::post('business/updateprofile', [App\Http\Controllers\BusinessController::class, 'UpdateBusinessProfile']);
    Route::post('admin/users', [App\Http\Controllers\AdminController::class, 'UsersList']);
    Route::post('admin/singleuser', [App\Http\Controllers\AdminController::class, 'SingleUser']);
    Route::post('admin/posts', [App\Http\Controllers\AdminController::class, 'Posts']);
    Route::post('admin/stories', [App\Http\Controllers\AdminController::class, 'Stories']);
    Route::post('admin/users/disable', [App\Http\Controllers\AdminController::class, 'DisableUser']);
    Route::post('business/chats', [App\Http\Controllers\MessagesController::class, 'BusinessChats']);
});
Route::middleware('auth:sanctum')->get('book', [BookController::class, 'index']);
Route::post('account/login', [AuthController::class, 'requestToken']);
Route::get('account/notlogin', [AuthController::class, 'NotLogin'])->name('login');
Route::post('account/sendemail', [AuthController::class, 'SendVEmail']);
Route::post('account/checkemail', [AuthController::class, 'CheckEmail']);
Route::post('account/checkname', [AuthController::class, 'CheckUsername']);
Route::post('account/register', [AuthController::class, 'Register']);
Route::post('account/verify', [AuthController::class, 'VerifyCode']);
Route::post('account/forget', [AuthController::class, 'ForgetPass']);
Route::post('weblogin', [App\Http\Controllers\AuthController::class, 'weblogin']);
